### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#11]
**go-micro**

*registry*
- [X] TTLs

*server*
- [X] re-register with TTLs

*TLS*
- [x] Registry
- [x] Transport
- [x] Broker

**go-platform**
- [x] Add event package
- [x] Add sync package
- [x] Log interface
- [x] Metrics interface
- [x] Router interface

*auth*
- [x] Implement interface (oauth2)
- [x] Add support for auth rpc service

**services**

- [x] auth-srv
- [x] event-srv
- [x] routing-srv
