### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#13]
**current task**:  Example services using platform

*demo*
- [x] API http://api.micro.pm
- [x] Web http://web.micro.pm
- [x] Sidecar http://proxy.micro.pm

*platform*
- [x] integrate dashboards into platform

*micro*
- [x] apache style access log
- [x] rudimentary stats 

*web*
- [x] Websockets
- [x] TLS
- [x] Set namespace via flags

*api*
- [x] TLS
- [x] CORS
- [x] Set namespace via flags

*sidecar*
- [x] TLS

**services**
- [x] db-srv

**dashboards**
- [x] open source dashboards
- [x] discovery
- [x] monitoring
- [x] trace
- [x] config
- [x] event
