### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asim** [micro/micro#1643]
A bunch of stuff we need to get done

- [ ] Add "url" to runtime service metadata so status returns the url we can call
- [x] Add "instances" to the runtime so we can run a number of replicas with `micro run --instances 3`
- [ ] Support a set of build in canonical services supported by micro (micro/services) e.g `micro run micro/inventory`
- [ ] Create lighter weight SDKs for running services with micro
- [ ] Support both http and gRPC routing out of the box via the api
- [ ] Add a /graphql handler to the api

Other potential things https://github.com/micro/micro/discussions/1642

**Comment by lambdaR** [comment]
- [ ]  check multi-service (snapshot) `micro stats service1 service2 service3`
- [ ]  check multi-service (dynamic/live) `micro stats --dynamic service1 service2 service3`
