### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#37]
**current task**:  N/A

**web**
- [x] Shell in UI

**go-micro**
- [x] Add some standard SelectFilters for label and version based routing
- [x] MQTT Broker
- [x] MDNS Registry

**go-platform**
- [x] Cleanup KV - Improve startup time

**blog posts**
- [x] Micro Bot
- [x] Micro Design Patterns
