### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#48]
**current task**:  N/A

**web**
- [ ] Support hostnames
- [ ] Reskin dashboard
- [x] Stats link

**api**
- [ ] Middleware

**bot**
- [ ] IMAP input
- [ ] Broker input
- [ ] Stream interface

**go-micro**
- [x] Add timeout and retry logic based on adrian cockcroft's ideas [here](http://www.slideshare.net/adriancockcroft/whats-missing-microservices-meetup-at-cisco)

**go-platform**
- [ ] Top level initialisation
- [ ] Add replicated log/data structure interface

**auth**
- [ ] implement IAM policies

**services**
- [ ] log-srv

**dashboards**
- [ ] auth
- [ ] log
- [ ] metrics

**misc**
- [ ] logistics demo
- [ ] nomad deployment

**blog posts**
- [ ] Micro on Kubernetes

**Comment by asim** [comment]
Close this. Using https://github.com/micro/micro/wiki/Roadmap instead.
