### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#6]
Just a place for stuff I'm currently working on

**misc**
- [x] Bug fixing
- [x] Gitbook style docs

**micro**
- [x] Add cli registration
- [x] Add architecture diagrams

*web*
- [x] Proxy to web apps

**go-micro**

*interface*
- [x] Change streaming interface to be bi-directional
- [x] mondo/[mercury](https://github.com/mondough/mercury) integration
- [x] Add String() method to all interfaces

*registry*
- [x] Timeout option

*broker*
- [x] ack messages
- [x] distributed queuing

*discovery*
- [x] Define the interface
- [x] TTLs and heartbeating for discovery
- [x] Caching in discovery; use the watcher
- [x] Pub discovery events
- [x] Prepopulate the discovery cache
- [x] Add registry options

*selector*
- [x] NodeSelector for the Client
- [x] Selector interface
- [x] Host pool/node blacklisting selector

**go-platform**

- [x] initial discovery interface
- [x] initial monitoring interface
- [x] initial trace interface

**Comment by asim** [comment]
Close and create new list
