### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by asim** [micro/micro#8]
**current task**: Config

**micro**
- [x] Move endpoints to single shared internal package
- [x] Cleanup cli code

*web*
- [x] Display "web" services on index page

**go-micro**

*interface*
- [x] Top level initialisation
- [x] Make options public so they can be used in other implementations

*client*
- [x] Retry Option
- [x] DialTimeout Option
- [x] RequestTimeout Option

*server*
- [x] support for "internal" endpoints that are not exposed 

*kv*
- [x] consistent hashed distributed in memory kv

*config*
- [x] implement interface
- [x] implement file source
- [x] implement example usage
- [x] create platform config-srv

**go-plugins**
- [x] NATS registry plugin

**docker**
- [x] rebuild all the images

**codegen**
- [x] Update interface from SendR/RecvR to Send/Recv

**Comment by asim** [comment]
Close and start fresh
